            - name: Netlify Deploy
  # You may pin to the exact commit or the version.
  # uses: jsmrcaga/action-netlify-deploy@0f0941d68f55a7268a8258b2a367190f17116a39
  uses: jsmrcaga/action-netlify-deploy@v2.2.0
  with:
    # Auth token to use with netlify
    NETLIFY_AUTH_TOKEN: # default is 
    # Your Netlify site id
    NETLIFY_SITE_ID: # default is 
    # Should the site be deployed to production?
    NETLIFY_DEPLOY_TO_PROD: # optional
    # A deploy message
    NETLIFY_DEPLOY_MESSAGE: # optional, default is 
    # When provided, prints more debug info in NETLIFY_OUTPUT
    debug: # optional, default is 
    # Directory where built files are stored
    build_directory: # default is build
    # Directory where built files are stored
    functions_directory: # optional, default is 
    # Command to install dependencies
    install_command: # optional, default is 
    # Path to netlify CLI binary
    netlify_path: # optional, default is netlify
    # Command to build static website
    build_command: # optional, default is npm run build
    # Deployment Subdomain name
    deploy_alias: # optional, default is 
    # In monorepos, package to deploy
    monorepo_package: # optional, default is 
    # Any optional extra flags added to Netlify deploy command
    command_extra_flags: # optional, default is 
          
